-- Maternal Care - Patient appointment booking compatibility notice
--
-- The executable installation source is now:
--   supabase/migrations/20260920160000_patient_booking_request_review_workflow.sql
--
-- That additive migration upgrades the existing
-- public.create_patient_appointment_request table, replaces the compatible
-- create_patient_appointment_request(...) RPC body, and installs the secure
-- Doctor accept/decline RPCs and RLS policies.
--
-- This former manual installer intentionally contains no executable SQL so it
-- cannot restore the retired behavior that inserted unreviewed Patient
-- requests directly into public.schedule.
