-- Run this in the Supabase SQL Editor.
-- Creates and configures staff profile tables used by the Staff Profile page.

create extension if not exists pgcrypto;

create table if not exists public.staff_personal_information (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  auth_user_id uuid not null,
  full_name text,
  birthdate date,
  civil_status text,
  gender text,
  nationality text,
  years_of_experience integer default 0,
  updated_at timestamptz not null default now()
);

alter table public.staff_personal_information
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists auth_user_id uuid,
  add column if not exists full_name text,
  add column if not exists birthdate date,
  add column if not exists civil_status text,
  add column if not exists gender text,
  add column if not exists nationality text,
  add column if not exists years_of_experience integer default 0,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.staff_professional_information (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  auth_user_id uuid not null,
  staff_code text,
  license_number text,
  board_certification text,
  email_address text,
  contact_number text,
  clinic_hospital_name text,
  clinic_address text,
  updated_at timestamptz not null default now()
);

alter table public.staff_professional_information
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists auth_user_id uuid,
  add column if not exists staff_code text,
  add column if not exists license_number text,
  add column if not exists board_certification text,
  add column if not exists email_address text,
  add column if not exists contact_number text,
  add column if not exists clinic_hospital_name text,
  add column if not exists clinic_address text,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_staff_personal_information_auth_user_id
  on public.staff_personal_information(auth_user_id);

create index if not exists idx_staff_professional_information_auth_user_id
  on public.staff_professional_information(auth_user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.staff_personal_information to authenticated;
grant select, insert, update, delete on public.staff_professional_information to authenticated;

alter table public.staff_personal_information enable row level security;
alter table public.staff_professional_information enable row level security;

drop policy if exists "Staff users can manage own personal information"
  on public.staff_personal_information;

create policy "Staff users can manage own personal information"
on public.staff_personal_information
for all
to authenticated
using (auth_user_id = auth.uid())
with check (auth_user_id = auth.uid());

drop policy if exists "Staff users can manage own professional information"
  on public.staff_professional_information;

create policy "Staff users can manage own professional information"
on public.staff_professional_information
for all
to authenticated
using (auth_user_id = auth.uid())
with check (auth_user_id = auth.uid());

drop policy if exists "Admins can manage staff personal information"
  on public.staff_personal_information;

create policy "Admins can manage staff personal information"
on public.staff_personal_information
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and lower(profiles.role) = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and lower(profiles.role) = 'admin'
  )
);

drop policy if exists "Admins can manage staff professional information"
  on public.staff_professional_information;

create policy "Admins can manage staff professional information"
on public.staff_professional_information
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and lower(profiles.role) = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and lower(profiles.role) = 'admin'
  )
);

notify pgrst, 'reload schema';
