import { formatAppointmentDate, formatAppointmentTime } from "../../lib/appointmentDate";
import { formatReportTimestamp } from "../../lib/reportExport";
import { PrintableMetricGrid, PrintableReportFooter, PrintableReportHeader, PrintableReportPortal } from "./PrintableReportLayout";

export default function AppointmentSummaryPrintableReport({ patient, doctorName, generatedAt, summary }) {
  const details = [
    { label: "Patient", value: patient.full_name || "Patient" },
    { label: "Patient ID", value: patient.patient_id || patient.patient_code || "Not provided" },
    { label: "Generated", value: formatReportTimestamp(generatedAt) },
  ];
  if (doctorName && doctorName !== "Doctor") details.push({ label: "Generated by", value: doctorName });
  return (
    <PrintableReportPortal className="report-print-appointments">
      <PrintableReportHeader title="Appointment Summary" details={details} />
      <PrintableMetricGrid title="Appointment Statistics" metrics={summary.metrics} />
      {summary.additionalNote ? <p>{summary.additionalNote}</p> : null}
      <section className="report-print-section">
        <h2>Appointment History</h2>
        <table>
          <thead><tr><th>Date</th><th>Time</th><th>Gestational Age*</th><th>Doctor</th><th>Purpose / Appointment Type</th><th>Status</th></tr></thead>
          <tbody>
            {summary.historyAppointments.map(appointment => (
              <tr key={appointment.id}>
                <td>{formatAppointmentDate(appointment.start_time, { month: "2-digit", day: "2-digit", year: "numeric" })}</td>
                <td>{formatAppointmentTime(appointment.start_time)}</td>
                <td>{appointment.recordedGestationalAge}</td>
                <td>{appointment.resolved_doctor_name || "Doctor not recorded"}</td>
                <td>{appointment.title || "Appointment"}</td>
                <td>{appointment.classification.displayStatus}</td>
              </tr>
            ))}
            {!summary.historyAppointments.length ? <tr><td colSpan="6">No appointment history found.</td></tr> : null}
          </tbody>
        </table>
        {summary.historyAppointments.length ? <p>*Gestational age reflects the value recorded for the linked completed clinical visit when available.</p> : null}
      </section>
      <PrintableReportFooter generatedAt={generatedAt} />
    </PrintableReportPortal>
  );
}
