import { createPortal } from "react-dom";
import { formatReportTimestamp } from "../../lib/reportExport";
import "../../styles/report-print.css";

export function PrintableReportPortal({ className, children }) {
  if (typeof document === "undefined") return null;

  return createPortal(
    <article className={`report-print-root ${className || ""}`}>
      {children}
    </article>,
    document.body
  );
}

export function PrintableReportHeader({ title, details }) {
  return (
    <header className="report-print-header">
      <div>
        <strong>Maternal Care</strong>
        <span>Reminder &amp; Appointment Management System</span>
      </div>
      <h1>{title}</h1>
      <dl>
        {details.map((detail) => (
          <div key={detail.label}>
            <dt>{detail.label}</dt>
            <dd>{detail.value}</dd>
          </div>
        ))}
      </dl>
    </header>
  );
}

export function PrintableReportFooter({ generatedAt }) {
  return (
    <footer className="report-print-footer">
      <p>Generated by Maternal Care Reminder &amp; Appointment Management System</p>
      <p>For authorized clinical use.</p>
      <p>Generated: {formatReportTimestamp(generatedAt)}</p>
    </footer>
  );
}

export function PrintableMetricGrid({ title, metrics }) {
  return (
    <section className="report-print-section report-print-metrics">
      <h2>{title}</h2>
      <div>
        {metrics.map((metric) => (
          <article key={metric.label}>
            <span>{metric.label}</span>
            <strong>{metric.value}</strong>
            {metric.note ? <small>{metric.note}</small> : null}
          </article>
        ))}
      </div>
    </section>
  );
}
