
-- Separate Patient booking requests from confirmed clinic schedules.
--
-- Patient submissions are stored in public.create_patient_appointment_request.
-- A Doctor acceptance atomically creates public.schedule and marks the request
-- accepted. A decline only changes the request status. Existing schedule rows
-- are never deleted.

begin;

create table if not exists public.create_patient_appointment_request (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  patient_id uuid,
  patient_name text,
  doctor_id uuid,
  doctor_name text,
  title text,
  category text,
  description text,
  start_time timestamptz,
  end_time timestamptz,
  status text not null default 'pending',
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid
);

alter table public.create_patient_appointment_request
  add column if not exists created_at timestamptz default now(),
  add column if not exists patient_id uuid,
  add column if not exists patient_name text,
  add column if not exists doctor_id uuid,
  add column if not exists doctor_name text,
  add column if not exists title text,
  add column if not exists category text,
  add column if not exists description text,
  add column if not exists start_time timestamptz,
  add column if not exists end_time timestamptz,
  add column if not exists status text default 'pending',
  add column if not exists updated_at timestamptz default now(),
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by uuid;

-- Match schedule_id to the live public.schedule primary-key type instead of
-- assuming that every installation uses the same identifier type.
do $request_schedule_id$
declare
  v_schedule_id_type text;
begin
  if not exists (
    select 1
    from pg_catalog.pg_attribute
    where attrelid = 'public.create_patient_appointment_request'::pg_catalog.regclass
      and attname = 'schedule_id'
      and not attisdropped
  ) then
    select pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
      into v_schedule_id_type
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.schedule'::pg_catalog.regclass
      and attribute.attname = 'id'
      and not attribute.attisdropped;

    if v_schedule_id_type is null then
      raise exception 'public.schedule.id is required before installing Patient booking requests.';
    end if;

    execute pg_catalog.format(
      'alter table public.create_patient_appointment_request add column schedule_id %s',
      v_schedule_id_type
    );
  end if;
end;
$request_schedule_id$;

-- The table visible in the existing project uses bigint ids. Existing
-- PostgreSQL IDENTITY columns already generate values and must not receive
-- an additional sequence/default. Only plain bigint ids with neither an
-- identity definition nor a default receive the compatibility sequence.
do $request_id_default$
declare
  v_next_id bigint;
  v_is_identity boolean := false;
  v_has_default boolean := false;
begin
  select
    (attribute.attidentity in ('a', 'd')),
    (attribute_default.adbin is not null)
  into
    v_is_identity,
    v_has_default
  from pg_catalog.pg_attribute as attribute
  left join pg_catalog.pg_attrdef as attribute_default
    on attribute_default.adrelid = attribute.attrelid
   and attribute_default.adnum = attribute.attnum
  where attribute.attrelid =
    'public.create_patient_appointment_request'::pg_catalog.regclass
    and attribute.attname = 'id'
    and not attribute.attisdropped;

  if not coalesce(v_is_identity, false)
     and not coalesce(v_has_default, false) then
    create sequence if not exists public.create_patient_appointment_request_id_seq;

    select coalesce(max(id), 0) + 1
      into v_next_id
    from public.create_patient_appointment_request;

    perform pg_catalog.setval(
      'public.create_patient_appointment_request_id_seq'::pg_catalog.regclass,
      greatest(v_next_id, 1),
      false
    );

    alter table public.create_patient_appointment_request
      alter column id set default
      nextval('public.create_patient_appointment_request_id_seq'::pg_catalog.regclass);

    alter sequence public.create_patient_appointment_request_id_seq
      owned by public.create_patient_appointment_request.id;
  end if;
end;
$request_id_default$;

update public.create_patient_appointment_request
set status = 'pending'
where status is null or pg_catalog.btrim(status) = '';

update public.create_patient_appointment_request
set created_at = now()
where created_at is null;

update public.create_patient_appointment_request
set updated_at = coalesce(created_at, now())
where updated_at is null;

alter table public.create_patient_appointment_request
  alter column status set default 'pending',
  alter column status set not null,
  alter column created_at set default now(),
  alter column updated_at set default now();

do $request_status_constraint$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.create_patient_appointment_request'::pg_catalog.regclass
      and conname = 'patient_appointment_request_status_check'
  ) then
    alter table public.create_patient_appointment_request
      add constraint patient_appointment_request_status_check
      check (pg_catalog.lower(pg_catalog.btrim(status)) in ('pending', 'accepted', 'declined'))
      not valid;
  end if;
end;
$request_status_constraint$;

create index if not exists patient_appointment_request_patient_idx
  on public.create_patient_appointment_request (patient_id, created_at desc);

create index if not exists patient_appointment_request_doctor_status_idx
  on public.create_patient_appointment_request (doctor_id, status, start_time);

create unique index if not exists patient_appointment_request_schedule_key
  on public.create_patient_appointment_request (schedule_id)
  where schedule_id is not null;

create or replace function public.set_patient_appointment_request_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_patient_appointment_request_updated_at
  on public.create_patient_appointment_request;
create trigger set_patient_appointment_request_updated_at
before update on public.create_patient_appointment_request
for each row execute function public.set_patient_appointment_request_updated_at();

-- Preserve legacy pending request rows without deleting them. They are copied
-- to the request table and retain a schedule_id link. The new UI hides the
-- legacy schedule row until it is accepted or declined.
create or replace function pg_temp.safe_request_json(value text)
returns jsonb
language plpgsql
immutable
as $$
begin
  return coalesce(value, '{}')::jsonb;
exception
  when others then return '{}'::jsonb;
end;
$$;

insert into public.create_patient_appointment_request (
  patient_id,
  patient_name,
  doctor_id,
  doctor_name,
  title,
  category,
  description,
  start_time,
  end_time,
  status,
  schedule_id,
  created_at,
  updated_at
)
select
  schedule.patient_id,
  schedule.patient_name,
  schedule.doctor_id,
  schedule.doctor_name,
  schedule.title,
  nullif(details.value ->> 'category', ''),
  nullif(details.value ->> 'notes', ''),
  schedule.start_time,
  schedule.end_time,
  'pending',
  schedule.id,
  coalesce(schedule.created_at, now()),
  now()
from public.schedule as schedule
cross join lateral (
  select pg_temp.safe_request_json(schedule.description) as value
) as details
where (
    details.value ->> 'source' = 'patient-booking-request'
    or details.value ->> 'requestedByPatient' = 'true'
  )
  and pg_catalog.lower(pg_catalog.btrim(coalesce(details.value ->> 'requestStatus', 'pending')))
    not in ('accepted', 'declined', 'rejected')
  and pg_catalog.lower(pg_catalog.btrim(coalesce(schedule.status, 'scheduled')))
    not in ('cancel', 'cancelled', 'canceled', 'completed', 'complete', 'no_show', 'no show')
on conflict (schedule_id) where schedule_id is not null do nothing;

-- Replace any pre-existing request-table policies with explicit ownership and
-- assignment rules. Mutations are RPC-only; authenticated users receive SELECT.
alter table public.create_patient_appointment_request enable row level security;

do $drop_request_policies$
declare
  v_policy record;
begin
  for v_policy in
    select policyname
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'create_patient_appointment_request'
  loop
    execute pg_catalog.format(
      'drop policy %I on public.create_patient_appointment_request',
      v_policy.policyname
    );
  end loop;
end;
$drop_request_policies$;

create policy "Patients can read own appointment requests"
on public.create_patient_appointment_request
for select
to authenticated
using (
  exists (
    select 1
    from public.patients as patient
    where patient.user_id = auth.uid()
      and patient.id::text = create_patient_appointment_request.patient_id::text
  )
);

create policy "Doctors can read assigned appointment requests"
on public.create_patient_appointment_request
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profile
    where profile.id = auth.uid()
      and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.role, ''))) = 'doctor'
      and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.account_status, 'active')))
        not in ('inactive', 'deactivated', 'disabled', 'suspended', 'archived', 'deleted')
  )
  and (doctor_id is null or doctor_id = auth.uid())
);

create policy "Staff and admins can read appointment requests"
on public.create_patient_appointment_request
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profile
    where profile.id = auth.uid()
      and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.role, ''))) in ('staff', 'admin')
      and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.account_status, 'active')))
        not in ('inactive', 'deactivated', 'disabled', 'suspended', 'archived', 'deleted')
  )
);

revoke all on table public.create_patient_appointment_request from anon;
revoke insert, update, delete, truncate, references, trigger
  on table public.create_patient_appointment_request from authenticated;
grant select on table public.create_patient_appointment_request to authenticated;

create or replace function public.create_patient_appointment_request(
  p_doctor_id uuid,
  p_doctor_name text,
  p_title text,
  p_category text,
  p_start_time timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_patient public.patients%rowtype;
  v_doctor_name text;
  v_end_time timestamptz;
  v_request_id public.create_patient_appointment_request.id%type;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select patient.*
    into v_patient
  from public.patients as patient
  where patient.user_id = auth.uid()
  limit 1;

  if v_patient.id is null then
    raise exception 'No Patient record is linked to this account.' using errcode = '42501';
  end if;

  if p_start_time is null or p_start_time <= now() then
    raise exception 'Choose an appointment time in the future.' using errcode = '22023';
  end if;

  if nullif(pg_catalog.btrim(coalesce(p_title, '')), '') is null then
    raise exception 'Appointment type is required.' using errcode = '22023';
  end if;

  if p_doctor_id is not null then
    select coalesce(
      nullif(pg_catalog.btrim(personal.full_name), ''),
      nullif(pg_catalog.btrim(doctor_profile.full_name), ''),
      nullif(pg_catalog.btrim(p_doctor_name), ''),
      'Clinic doctor'
    )
      into v_doctor_name
    from public.profiles as doctor_profile
    left join public.doctor_personal_information as personal
      on personal.auth_user_id = doctor_profile.id
    where doctor_profile.id = p_doctor_id
      and pg_catalog.lower(pg_catalog.btrim(coalesce(doctor_profile.role, ''))) = 'doctor'
      and pg_catalog.lower(pg_catalog.btrim(coalesce(doctor_profile.account_status, 'active')))
        not in ('inactive', 'deactivated', 'disabled', 'suspended', 'archived', 'deleted');

    if v_doctor_name is null then
      raise exception 'The selected Doctor is not available.' using errcode = '22023';
    end if;
  else
    v_doctor_name := coalesce(
      nullif(pg_catalog.btrim(p_doctor_name), ''),
      'Available clinic doctor'
    );
  end if;

  v_end_time := p_start_time + interval '30 minutes';

  if exists (
    select 1
    from public.create_patient_appointment_request as request
    where request.patient_id::text = v_patient.id::text
      and pg_catalog.lower(pg_catalog.btrim(request.status)) = 'pending'
      and request.start_time < v_end_time
      and request.end_time > p_start_time
  ) then
    raise exception 'You already have a pending appointment request during this time.'
      using errcode = '23505';
  end if;

  if exists (
    select 1
    from public.schedule as schedule
    where schedule.patient_id::text = v_patient.id::text
      and pg_catalog.lower(pg_catalog.btrim(coalesce(schedule.status, 'scheduled'))) not in (
        'cancel', 'cancelled', 'canceled', 'no_show', 'no show', 'completed', 'complete'
      )
      and schedule.start_time < v_end_time
      and schedule.end_time > p_start_time
  ) then
    raise exception 'You already have an appointment during this time.' using errcode = '23505';
  end if;

  insert into public.create_patient_appointment_request (
    patient_id,
    patient_name,
    doctor_id,
    doctor_name,
    title,
    category,
    start_time,
    end_time,
    status
  )
  values (
    v_patient.id,
    coalesce(nullif(pg_catalog.btrim(v_patient.full_name), ''), 'Patient'),
    p_doctor_id,
    v_doctor_name,
    pg_catalog.btrim(p_title),
    coalesce(nullif(pg_catalog.btrim(p_category), ''), 'appointment'),
    p_start_time,
    v_end_time,
    'pending'
  )
  returning id into v_request_id;

  return pg_catalog.jsonb_build_object(
    'id', v_request_id,
    'request_id', v_request_id,
    'status', 'pending'
  );
end;
$$;

create or replace function public.accept_patient_appointment_request(
  p_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_request public.create_patient_appointment_request%rowtype;
  v_doctor_name text;
  v_doctor_id uuid;
  v_end_time timestamptz;
  v_schedule_id public.schedule.id%type;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select coalesce(
    nullif(pg_catalog.btrim(personal.full_name), ''),
    nullif(pg_catalog.btrim(profile.full_name), ''),
    'Clinic doctor'
  )
    into v_doctor_name
  from public.profiles as profile
  left join public.doctor_personal_information as personal
    on personal.auth_user_id = profile.id
  where profile.id = auth.uid()
    and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.role, ''))) = 'doctor'
    and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.account_status, 'active')))
      not in ('inactive', 'deactivated', 'disabled', 'suspended', 'archived', 'deleted');

  if v_doctor_name is null then
    raise exception 'Only an active Doctor can accept appointment requests.' using errcode = '42501';
  end if;

  select request.*
    into v_request
  from public.create_patient_appointment_request as request
  where request.id = p_request_id
  for update;

  if v_request.id is null then
    raise exception 'Appointment request was not found.' using errcode = 'P0002';
  end if;

  if pg_catalog.lower(pg_catalog.btrim(coalesce(v_request.status, ''))) <> 'pending' then
    raise exception 'Only pending appointment requests can be accepted.' using errcode = '22023';
  end if;

  if v_request.doctor_id is not null and v_request.doctor_id <> auth.uid() then
    raise exception 'This appointment request is assigned to another Doctor.' using errcode = '42501';
  end if;

  if v_request.patient_id is null or not exists (
    select 1 from public.patients as patient where patient.id::text = v_request.patient_id::text
  ) then
    raise exception 'The request is not linked to a valid Patient record.' using errcode = '23503';
  end if;

  if v_request.start_time is null or v_request.start_time <= now() then
    raise exception 'The requested appointment time is no longer in the future.' using errcode = '22023';
  end if;

  v_doctor_id := auth.uid();
  v_end_time := case
    when v_request.end_time is not null and v_request.end_time > v_request.start_time
      then v_request.end_time
    else v_request.start_time + interval '30 minutes'
  end;

  if exists (
    select 1
    from public.schedule as schedule
    where schedule.patient_id::text = v_request.patient_id::text
      and (v_request.schedule_id is null or schedule.id <> v_request.schedule_id)
      and pg_catalog.lower(pg_catalog.btrim(coalesce(schedule.status, 'scheduled'))) not in (
        'cancel', 'cancelled', 'canceled', 'no_show', 'no show', 'completed', 'complete'
      )
      and schedule.start_time < v_end_time
      and schedule.end_time > v_request.start_time
  ) then
    raise exception 'The Patient already has an appointment during this time.' using errcode = '23505';
  end if;

  if exists (
    select 1
    from public.schedule as schedule
    where schedule.doctor_id = v_doctor_id
      and (v_request.schedule_id is null or schedule.id <> v_request.schedule_id)
      and pg_catalog.lower(pg_catalog.btrim(coalesce(schedule.status, 'scheduled'))) not in (
        'cancel', 'cancelled', 'canceled', 'no_show', 'no show', 'completed', 'complete'
      )
      and schedule.start_time < v_end_time
      and schedule.end_time > v_request.start_time
  ) then
    raise exception 'That appointment slot is no longer available.' using errcode = '23505';
  end if;

  if v_request.schedule_id is not null then
    update public.schedule
    set patient_id = v_request.patient_id,
        patient_name = coalesce(nullif(pg_catalog.btrim(v_request.patient_name), ''), 'Patient'),
        doctor_id = v_doctor_id,
        doctor_name = v_doctor_name,
        title = pg_catalog.btrim(v_request.title),
        description = pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object(
          'category', coalesce(nullif(pg_catalog.btrim(v_request.category), ''), 'appointment'),
          'notes', nullif(pg_catalog.btrim(v_request.description), ''),
          'source', 'patient-booking-request',
          'requestStatus', 'accepted',
          'bookingRequestId', v_request.id
        ))::text,
        start_time = v_request.start_time,
        end_time = v_end_time,
        status = 'scheduled'
    where id = v_request.schedule_id
    returning id into v_schedule_id;
  end if;

  if v_schedule_id is null then
    insert into public.schedule (
      patient_id,
      patient_name,
      doctor_id,
      doctor_name,
      title,
      description,
      start_time,
      end_time,
      status
    )
    values (
      v_request.patient_id,
      coalesce(nullif(pg_catalog.btrim(v_request.patient_name), ''), 'Patient'),
      v_doctor_id,
      v_doctor_name,
      pg_catalog.btrim(v_request.title),
      pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object(
        'category', coalesce(nullif(pg_catalog.btrim(v_request.category), ''), 'appointment'),
        'notes', nullif(pg_catalog.btrim(v_request.description), ''),
        'source', 'patient-booking-request',
        'requestStatus', 'accepted',
        'bookingRequestId', v_request.id
      ))::text,
      v_request.start_time,
      v_end_time,
      'scheduled'
    )
    returning id into v_schedule_id;
  end if;

  update public.create_patient_appointment_request
  set status = 'accepted',
      doctor_id = v_doctor_id,
      doctor_name = v_doctor_name,
      schedule_id = v_schedule_id,
      reviewed_at = now(),
      reviewed_by = auth.uid()
  where id = v_request.id;

  return pg_catalog.jsonb_build_object(
    'request_id', v_request.id,
    'schedule_id', v_schedule_id,
    'patient_id', v_request.patient_id,
    'status', 'accepted'
  );
end;
$$;

create or replace function public.decline_patient_appointment_request(
  p_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_request public.create_patient_appointment_request%rowtype;
  v_is_active_doctor boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select exists (
    select 1
    from public.profiles as profile
    where profile.id = auth.uid()
      and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.role, ''))) = 'doctor'
      and pg_catalog.lower(pg_catalog.btrim(coalesce(profile.account_status, 'active')))
        not in ('inactive', 'deactivated', 'disabled', 'suspended', 'archived', 'deleted')
  ) into v_is_active_doctor;

  if not v_is_active_doctor then
    raise exception 'Only an active Doctor can decline appointment requests.' using errcode = '42501';
  end if;

  select request.*
    into v_request
  from public.create_patient_appointment_request as request
  where request.id = p_request_id
  for update;

  if v_request.id is null then
    raise exception 'Appointment request was not found.' using errcode = 'P0002';
  end if;

  if pg_catalog.lower(pg_catalog.btrim(coalesce(v_request.status, ''))) <> 'pending' then
    raise exception 'Only pending appointment requests can be declined.' using errcode = '22023';
  end if;

  if v_request.doctor_id is not null and v_request.doctor_id <> auth.uid() then
    raise exception 'This appointment request is assigned to another Doctor.' using errcode = '42501';
  end if;

  update public.create_patient_appointment_request
  set status = 'declined',
      reviewed_at = now(),
      reviewed_by = auth.uid()
  where id = v_request.id;

  -- Legacy requests may already have a schedule row from the former workflow.
  -- Keep the audit row, but make it inactive and retain declined metadata.
  if v_request.schedule_id is not null then
    update public.schedule
    set status = 'cancelled',
        description = pg_catalog.jsonb_strip_nulls(pg_catalog.jsonb_build_object(
          'category', coalesce(nullif(pg_catalog.btrim(v_request.category), ''), 'appointment'),
          'notes', nullif(pg_catalog.btrim(v_request.description), ''),
          'source', 'patient-booking-request',
          'requestStatus', 'declined',
          'bookingRequestId', v_request.id
        ))::text
    where id = v_request.schedule_id;
  end if;

  return pg_catalog.jsonb_build_object(
    'request_id', v_request.id,
    'status', 'declined'
  );
end;
$$;

revoke all on function public.create_patient_appointment_request(uuid, text, text, text, timestamptz)
  from public, anon;
grant execute on function public.create_patient_appointment_request(uuid, text, text, text, timestamptz)
  to authenticated;

revoke all on function public.accept_patient_appointment_request(bigint)
  from public, anon;
grant execute on function public.accept_patient_appointment_request(bigint)
  to authenticated;

revoke all on function public.decline_patient_appointment_request(bigint)
  from public, anon;
grant execute on function public.decline_patient_appointment_request(bigint)
  to authenticated;

do $request_realtime$
begin
  if not exists (
    select 1
    from pg_catalog.pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'create_patient_appointment_request'
  ) then
    alter publication supabase_realtime
      add table public.create_patient_appointment_request;
  end if;
end;
$request_realtime$;

notify pgrst, 'reload schema';

commit;
